application: andy-keller
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /font
  static_dir: static/font

- url: /img
  static_dir: static/img

- url: /slick
  static_dir: static/slick

- url: /templates
  static_dir: static/templates

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
